[project]
name = "mea-rasterplotter"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arjan Mossel", email = "arjanmossel@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.20.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "polars>=1.38.1",
]

[project.optional-dependencies]
marimo-ai = [
    "pydantic-ai>=1.73.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "ty>=0.0.72",
]

[tool.ruff.lint]
ignore = [
    "PLR1711", # Useless returns: used by Marimo to delimit the end of a cell.
    "B018", # The last expression of a Marimo cell is the cell's visual output
]
