[project]
name = "mea-rasterplotter"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arjan Mossel", email = "arjanmossel@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "marimo>=0.20.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "polars>=1.38.1",
]

[dependency-groups]
dev = [
    "pydantic-ai>=1.73.0",
]
